# Generated by Django 5.0.6 on 2024-06-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(choices=[('Arrived', 'Arrived')], max_length=20),
        ),
    ]
