# Generated by Django 5.0.6 on 2024-05-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='code',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
