# Generated by Django 5.0.6 on 2024-05-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_colormodel_code_alter_colormodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='images',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='image2',
            field=models.ImageField(null=True, upload_to='product-images'),
        ),
    ]
