# Generated by Django 5.0.6 on 2024-05-30 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_images_productsmodel_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
