# Generated by Django 5.0.6 on 2024-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimagesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='long_detail_description',
            field=models.TextField(null=True),
        ),
    ]
